# Generated by Django 4.0.3 on 2022-05-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='degree',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
