# Generated by Django 4.0.3 on 2022-05-12 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('degree', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('complet_date', models.DateField(auto_now_add=True)),
                ('lecture_time', models.CharField(max_length=20)),
                ('learning_time', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('before', 'before'), ('ongoing', 'ongoing'), ('completed', 'completed')], max_length=20)),
                ('url', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notes_lecture', serialize=False, to='subject.lecture')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pf_name', models.CharField(blank=True, max_length=20, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_lecture', to='subject.subject'),
        ),
    ]
