# Generated by Django 4.0.3 on 2022-06-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.UniqueConstraint(fields=('student', 'video_id'), name='unique_lecture'),
        ),
    ]
