# Generated by Django 4.0.3 on 2022-06-09 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_alter_notes_content_alter_notes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_lecture', to='subject.lecture', unique=True),
        ),
    ]
